id: I62379B9A
legacy_id: P006682
ocr_import_info:
  bdrc_scan_id: W26673
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T02:51:22'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:47:20.973543+00:00'
last_modified: 2022-09-02 14:53:02.861765
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W26673
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW26673
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བརྩོན་འགྲུས་གྲགས་པ།
  author: བླ་མ་ཞང་བརྩོན་འགྲུས་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9132160650153188
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4186:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4186
      total_pages: 742
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4186.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9110517130018172
    legacy_id: v004
  I4185:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4185
      total_pages: 758
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4185.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9094208439950194
    legacy_id: v003
  I4183:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4183
      total_pages: 782
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4183.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9102003931966086
    legacy_id: v001
  I4187:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4187
      total_pages: 732
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4187.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.91527311712767
    legacy_id: v005
  I4191:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4191
      total_pages: 548
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I4191.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9060127994857733
    legacy_id: v009
  I4188:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4188
      total_pages: 758
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4188.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9084954255483978
    legacy_id: v006
  I4189:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4189
      total_pages: 802
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4189.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9096059309272846
    legacy_id: v007
  I4190:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4190
      total_pages: 652
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4190.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9210479277370937
    legacy_id: v008
  I4184:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4184
      total_pages: 768
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4184.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9233053347620732
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
